stages:
  - deploy
variables:
  DOCKER_DRIVER: overlay2
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle

deploy:
  image: quay.io/openshift/origin-cli:4.5
  stage: deploy
  script:
    - oc login --token=$OC_TOKEN  https://api.okd.perm.ertelecom.ru:6443 --insecure-skip-tls-verify
    - oc process -f okd.yaml  -p CI_REGISTRY_IMAGE="$CI_REGISTRY_IMAGE"
      -p CI_COMMIT_REF_SLUG="1-0-8" -o yaml
    - oc process -f okd.yaml -o yaml  -p CI_REGISTRY_IMAGE="$CI_REGISTRY_IMAGE"
      -p CI_COMMIT_REF_SLUG="$CI_COMMIT_REF_SLUG" |
      oc apply	-f -
  tags:
    - k8s
