apiVersion: v1
kind: Template
metadata:
  name: er-logger-template
parameters:
  - name: CI_REGISTRY_IMAGE
    value: kafka-to-es
  - name: CI_COMMIT_REF_SLUG
    value: "1-0-8"
  - name: PORT
    value: "8080"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: er-logger-svc
  spec:
    selector:
      app: er-logger
    ports:
      - protocol: TCP
        port: 8080
    type: LoadBalancer
