apiVersion: v1
kind: Template
metadata:
  name: er-logger-template
parameters:
  - name: CI_REGISTRY_IMAGE
    value: kafka-to-es
  - name: CI_COMMIT_REF_SLUG
    value: master
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: er-logger
    labels:
      app: er-logger
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: er-logger
    template:
      metadata:
        labels:
          app: er-logger
          deploymentconfig: er-logger
      spec:
        imagePullSecrets:
          - name: registry.rd.ertelecom.ru
        containers:
          - resources:
              limits:
                memory: 512Mi

            name: er-logger
            image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
            ports:
              - containerPort: 8080
                protocol: TCP
            env:
              - name: KAFKA_HOST
                value: kafka-svc.prod:9092
              - name: KAFKA_TOPIC
                value: er-log
              - name: USE_SIMPLE_DECODER
                value: "1"

        restartPolicy: Always
        securityContext: {}
        schedulerName: default-scheduler
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
- apiVersion: v1
  kind: Service
  metadata:
    name: er-logger-svc
  spec:
    selector:
      app: er-logger
    ports:
      - protocol: TCP
        port: 8080
    type: LoadBalancer
