apiVersion: v1
kind: Template
metadata:
  name: er-logger-template
parameters:
  - name: CI_REGISTRY_IMAGE
    value: kafka-to-es
  - name: CI_COMMIT_REF_SLUG
    value: master
  - name: PORT
    value: 8080
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: er-logger-svc
  spec:
    selector:
      app: er-logger
    ports:
      - protocol: "TCP"
        port: ${PORT}
    type: LoadBalancer
