kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.nameSpace }}
  labels:
    app: {{ .Values.serviceName }}
    app.kubernetes.io/component: {{ .Values.serviceName }}
    app.kubernetes.io/instance: {{ .Values.serviceName }}
    app.kubernetes.io/part-of: {{ .Values.serviceNameApp }}
    app.openshift.io/runtime-namespace: {{ .Values.nameSpace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
        deploymentconfig: {{ .Values.serviceName }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      containers:
        - resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}

          name: {{ .Values.serviceName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.servicePort }}
              protocol: TCP
          env:
            - name: KAFKA_HOST
              value: {{ .Values.kafkaHost }}
            - name: KAFKA_TOPIC
              value: {{ .Values.kafkaTopic }}
            - name: USE_SIMPLE_DECODER
              value: {{ .Values.useSimpleDecoder }}
      restartPolicy: Always
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceNameSvc }}
spec:
  selector:
    app: {{ .Values.serviceName }}
  ports:
    - protocol: "TCP"
      port: {{ .Values.servicePort }}
  type: LoadBalancer
