kafka:
  host: ${KAFKA_HOST:kafka-svc.prod:9092}
  topic: ${KAFKA_TOPIC:er-log}

usesimpledecoder: ${USE_SIMPLE_DECODER:1}

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

  metrics:
    export:
      prometheus:
        enabled: true

  endpoints:
    web:
      exposure:
        include: prometheus
