FROM registry.rd.ertelecom.ru/devops/docker/alpine-oraclejdk8:latest

COPY build/libs/receiver-*.jar /app/receiver.jar

RUN apk add --update --no-cache busybox-extras curl bash

ENV JAVA_OPTS="-XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2" \
    SPRING_PROFILE="prod" \
    KAFKA_HOST="v.perm.ru:9093" \
    KAFKA_TOPIC="test"

RUN ls /app

CMD java \
    ${JAVA_OPTS} \
    -Dspring.profiles.active=${SPRING_PROFILE} \
    -jar /app/receiver.jar
